### ISSUE TITLE
テストケースの一部が SIGKILL されることがある

### ISSUE THREAD

**Issue by tomoki** [terry-u16/pahcer#7]
# 背景

AHC040 の期間中に幾つかのテストケースの実行が途中で SIGKILL される事象が何度か発生しました。
https://atcoder.jp/contests/ahc040

# 再現手順

以下のコマンドを実行します。

```
$ pacer run 
```

(手元の AHC のフォルダです。 https://github.com/user-attachments/files/18080946/ahc040-pahcer-debug.zip)

# 期待した結果

全てのテストケースが途中でキルされることなく 100/100 まで実行され、スコアが出力されること

# 実際に起こったこと

以下のように途中のテストケースが SIGKILL され、成功したテストが 99/100 などになる

```
$ while true; do pahcer run; done 
-- Configuring done (0.0s)
-- Generating done (0.0s)
-- Build files have been written to: /Users/tomoki/Dropbox/codes/contest/atcoder/ahc040/build
[100%] Built target main
|    Progress    | Seed |      Case Score       |     Average Score     |   Exec.   |
|                |      |   Score    | Relative |   Score    | Relative |   Time    |
|----------------|------|------------|----------|------------|----------|-----------|
| case   1 / 100 | 0000 |    772,656 |  100.000 |    772,656 |  100.000 |  1,990 ms |
| case   2 / 100 | 0002 |    691,502 |   99.873 |    732,079 |   99.937 |  2,528 ms |
| case   3 / 100 | 0004 |    709,475 |   99.486 |    724,544 |   99.786 |  3,255 ms |
| case   4 / 100 | 0006 |    853,676 |   99.915 |    756,827 |   99.819 |  3,258 ms |
| case   5 / 100 | 0007 |  1,037,018 |  100.000 |    812,865 |   99.855 |  3,261 ms |
| case   6 / 100 | 0003 |  1,262,160 |   99.447 |    887,748 |   99.787 |  3,304 ms |
| case   7 / 100 | 0001 |  1,416,519 |   99.050 |    963,287 |   99.682 |  3,323 ms |
| case   8 / 100 | 0005 |  1,120,344 |   99.582 |    982,919 |   99.669 |  3,326 ms |
| case   9 / 100 | 0008 |    954,663 |   97.325 |    979,779 |   99.409 |  3,012 ms |
| case  10 / 100 | 0010 |    860,134 |   99.928 |    967,815 |   99.461 |  1,943 ms |
| case  11 / 100 | 0009 |    986,377 |   99.031 |    969,502 |   99.422 |  3,040 ms |
| case  12 / 100 | 0013 |  1,037,097 |   99.864 |    975,135 |   99.458 |  2,944 ms |
| case  13 / 100 | 0011 |  1,276,266 |   99.493 |    998,299 |   99.461 |  3,047 ms |
| case  14 / 100 | 0015 |  1,012,377 |   96.945 |    999,305 |   99.281 |  2,994 ms |
| case  15 / 100 | 0014 |  1,186,666 |   97.635 |  1,011,795 |   99.172 |  3,027 ms |
| case  16 / 100 | 0012 |  1,109,246 |   99.504 |  1,017,886 |   99.192 |  3,128 ms |
| case  17 / 100 | 0022 |          0 |    0.000 |    958,010 |   93.358 |      0 ms |
Failed to run (signal: 9 (SIGKILL)). command: cd "./tools" && "cargo" "run" "--bin" "tester" "--release" "../build/main"
| case  18 / 100 | 0016 |    896,062 |   99.514 |    954,569 |   93.700 |  3,014 ms |
| case  19 / 100 | 0017 |  1,345,033 |   99.522 |    975,120 |   94.006 |  3,100 ms |
| case  20 / 100 | 0018 |  1,054,899 |   97.877 |    979,109 |   94.200 |  3,102 ms |
| case  21 / 100 | 0019 |    916,207 |   98.308 |    976,113 |   94.395 |  2,977 ms |
| case  22 / 100 | 0020 |    929,516 |   99.383 |    973,995 |   94.622 |  2,965 ms |
| case  23 / 100 | 0021 |  1,302,957 |   99.615 |    988,298 |   94.839 |  2,971 ms |
| case  24 / 100 | 0024 |  1,049,066 |   99.431 |    990,830 |   95.030 |  2,910 ms |
| case  25 / 100 | 0023 |  1,215,577 |   99.450 |    999,820 |   95.207 |  3,072 ms |
| case  26 / 100 | 0025 |    815,173 |  100.000 |    992,718 |   95.391 |  2,979 ms |
| case  27 / 100 | 0026 |  1,132,902 |   99.355 |    997,910 |   95.538 |  3,009 ms |
| case  28 / 100 | 0027 |  1,501,982 |   98.179 |  1,015,913 |   95.633 |  3,198 ms |
| case  29 / 100 | 0030 |    899,205 |   98.083 |  1,011,888 |   95.717 |  2,947 ms |
| case  30 / 100 | 0029 |  1,164,384 |   97.956 |  1,016,971 |   95.792 |  3,028 ms |
| case  31 / 100 | 0028 |  1,543,797 |   99.165 |  1,033,966 |   95.901 |  3,096 ms |
| case  32 / 100 | 0031 |  1,431,629 |   99.247 |  1,046,393 |   96.005 |  3,099 ms |
| case  33 / 100 | 0032 |  1,157,017 |   99.705 |  1,049,745 |   96.117 |  3,062 ms |
| case  34 / 100 | 0033 |  1,322,687 |   99.766 |  1,057,773 |   96.225 |  3,048 ms |
| case  35 / 100 | 0034 |  1,188,948 |   98.553 |  1,061,520 |   96.291 |  2,996 ms |
| case  36 / 100 | 0035 |  1,349,849 |   98.733 |  1,069,530 |   96.359 |  3,079 ms |
| case  37 / 100 | 0038 |    756,320 |   99.495 |  1,061,064 |   96.444 |  2,660 ms |
| case  38 / 100 | 0037 |  1,374,864 |   99.299 |  1,069,322 |   96.519 |  3,005 ms |
| case  39 / 100 | 0036 |  1,399,544 |   99.411 |  1,077,790 |   96.593 |  3,085 ms |
| case  40 / 100 | 0039 |  1,079,058 |   99.376 |  1,077,821 |   96.663 |  3,039 ms |
| case  41 / 100 | 0040 |  1,200,595 |   99.448 |  1,080,816 |   96.730 |  3,043 ms |
| case  42 / 100 | 0041 |    831,470 |   99.160 |  1,074,879 |   96.788 |  3,005 ms |
| case  43 / 100 | 0042 |  1,305,787 |   99.196 |  1,080,249 |   96.844 |  3,025 ms |
| case  44 / 100 | 0045 |    815,133 |   99.815 |  1,074,224 |   96.912 |  2,077 ms |
| case  45 / 100 | 0043 |    745,735 |   99.956 |  1,066,924 |   96.979 |  3,040 ms |
| case  46 / 100 | 0044 |    971,854 |   98.967 |  1,064,857 |   97.023 |  3,100 ms |
| case  47 / 100 | 0046 |  1,204,125 |   99.671 |  1,067,820 |   97.079 |  3,009 ms |
| case  48 / 100 | 0048 |    826,949 |   98.853 |  1,062,802 |   97.116 |  2,990 ms |
| case  49 / 100 | 0047 |  1,328,545 |   99.166 |  1,068,225 |   97.158 |  3,062 ms |
| case  50 / 100 | 0049 |    795,692 |   99.950 |  1,062,775 |   97.214 |  1,745 ms |
| case  51 / 100 | 0051 |  1,183,875 |   98.925 |  1,065,149 |   97.247 |  3,047 ms |
| case  52 / 100 | 0050 |  1,316,526 |   99.855 |  1,069,983 |   97.297 |  3,110 ms |
| case  53 / 100 | 0052 |  1,038,559 |   99.493 |  1,069,391 |   97.339 |  3,026 ms |
| case  54 / 100 | 0053 |    984,828 |   98.801 |  1,067,825 |   97.366 |  3,177 ms |
| case  55 / 100 | 0054 |    967,129 |   98.865 |  1,065,994 |   97.393 |  3,150 ms |
| case  56 / 100 | 0055 |  1,007,101 |   99.197 |  1,064,942 |   97.425 |  3,020 ms |
| case  57 / 100 | 0056 |  1,459,644 |   99.355 |  1,071,867 |   97.459 |  3,097 ms |
| case  58 / 100 | 0057 |    918,080 |  100.000 |  1,069,215 |   97.503 |  3,018 ms |
| case  59 / 100 | 0059 |  1,134,258 |   98.515 |  1,070,318 |   97.520 |  3,066 ms |
| case  60 / 100 | 0058 |  1,244,984 |   99.160 |  1,073,229 |   97.547 |  3,092 ms |
| case  61 / 100 | 0060 |  1,131,263 |   94.573 |  1,074,180 |   97.499 |  3,142 ms |
| case  62 / 100 | 0061 |  1,197,085 |   99.757 |  1,076,162 |   97.535 |  3,089 ms |
| case  63 / 100 | 0062 |  1,013,961 |   99.008 |  1,075,175 |   97.559 |  2,979 ms |
| case  64 / 100 | 0063 |  1,228,212 |   98.665 |  1,077,566 |   97.576 |  3,095 ms |
| case  65 / 100 | 0064 |  1,410,089 |   99.583 |  1,082,682 |   97.607 |  3,047 ms |
| case  66 / 100 | 0065 |  1,304,021 |   95.930 |  1,086,036 |   97.581 |  3,141 ms |
| case  67 / 100 | 0070 |    776,395 |   99.284 |  1,081,414 |   97.607 |  1,828 ms |
| case  68 / 100 | 0069 |    690,276 |   98.072 |  1,075,662 |   97.614 |  2,128 ms |
| case  69 / 100 | 0067 |  1,152,918 |   99.337 |  1,076,782 |   97.639 |  3,019 ms |
| case  70 / 100 | 0066 |  1,232,335 |   99.359 |  1,079,004 |   97.663 |  3,096 ms |
| case  71 / 100 | 0068 |    964,557 |   99.412 |  1,077,392 |   97.688 |  2,967 ms |
| case  72 / 100 | 0072 |    870,643 |   99.984 |  1,074,521 |   97.720 |  3,005 ms |
| case  73 / 100 | 0071 |    980,579 |   97.962 |  1,073,234 |   97.723 |  3,142 ms |
| case  74 / 100 | 0073 |    917,640 |   99.940 |  1,071,131 |   97.753 |  3,072 ms |
| case  75 / 100 | 0074 |  1,331,648 |   99.067 |  1,074,605 |   97.770 |  3,038 ms |
| case  76 / 100 | 0077 |    930,812 |   99.969 |  1,072,713 |   97.799 |  2,897 ms |
| case  77 / 100 | 0075 |    955,817 |   99.369 |  1,071,194 |   97.820 |  3,017 ms |
| case  78 / 100 | 0076 |  1,044,048 |   98.713 |  1,070,846 |   97.831 |  2,990 ms |
| case  79 / 100 | 0078 |    835,344 |   99.100 |  1,067,865 |   97.847 |  2,907 ms |
| case  80 / 100 | 0079 |  1,301,111 |   99.678 |  1,070,781 |   97.870 |  3,060 ms |
| case  81 / 100 | 0080 |  1,458,740 |   98.887 |  1,075,571 |   97.883 |  2,996 ms |
| case  82 / 100 | 0081 |  1,117,554 |   97.768 |  1,076,083 |   97.881 |  3,038 ms |
| case  83 / 100 | 0082 |    827,459 |   99.602 |  1,073,087 |   97.902 |  3,025 ms |
| case  84 / 100 | 0083 |  1,184,271 |   99.389 |  1,074,411 |   97.920 |  3,088 ms |
| case  85 / 100 | 0085 |  1,082,497 |   97.702 |  1,074,506 |   97.917 |  3,058 ms |
| case  86 / 100 | 0084 |  1,129,774 |   98.328 |  1,075,148 |   97.922 |  3,158 ms |
| case  87 / 100 | 0086 |  1,243,642 |   99.847 |  1,077,085 |   97.944 |  3,126 ms |
| case  88 / 100 | 0088 |    791,415 |   98.692 |  1,073,839 |   97.953 |  2,964 ms |
| case  89 / 100 | 0087 |  1,072,516 |   99.770 |  1,073,824 |   97.973 |  3,011 ms |
| case  90 / 100 | 0089 |    949,859 |   98.119 |  1,072,447 |   97.975 |  3,042 ms |
| case  91 / 100 | 0092 |    751,498 |  100.000 |  1,068,920 |   97.997 |  1,815 ms |
| case  92 / 100 | 0090 |  1,409,074 |   99.861 |  1,072,617 |   98.017 |  3,123 ms |
| case  93 / 100 | 0093 |  1,125,521 |   98.676 |  1,073,186 |   98.024 |  3,003 ms |
| case  94 / 100 | 0091 |  1,365,364 |   98.976 |  1,076,294 |   98.034 |  3,075 ms |
| case  95 / 100 | 0094 |  1,230,734 |   98.144 |  1,077,920 |   98.035 |  3,033 ms |
| case  96 / 100 | 0095 |  1,533,468 |   98.636 |  1,082,665 |   98.042 |  3,053 ms |
| case  97 / 100 | 0096 |  1,564,805 |   97.954 |  1,087,636 |   98.041 |  3,159 ms |
| case  98 / 100 | 0097 |  1,292,469 |   98.182 |  1,089,726 |   98.042 |  3,106 ms |
| case  99 / 100 | 0098 |  1,026,196 |   99.282 |  1,089,084 |   98.055 |  2,994 ms |
| case 100 / 100 | 0099 |    898,922 |   99.792 |  1,087,183 |   98.072 |  1,994 ms |
Average Score          : 1,087,183
Average Score (log10)  : 5.971
Average Relative Score : 98.072
Accepted               : 99 / 100
Max Execution Time     : 3,326 ms
pahcer run  223.63s user 7.58s system 613% cpu 37.670 total
```

# 再現頻度

記録していないため不明ですが、 体感 1/30 程度です。
再現手順が確立出来たらアップデートします。

# 環境

- OS: macOS 15.1.1 (24B91)
- cargo:  1.83.0 (5ffbef321 2024-10-29)
- pahcer: 0.1.1
-- `cargo install pahcer` でインストールしたもの

**Comment by tomoki** [comment]
同根と思われる問題で optuna の最適化が途中で失敗することもありました。以下ログです。

```
$ uv run optimize.py  
Using CPython 3.13.0 interpreter at: /opt/homebrew/opt/python@3.13/bin/python3.13
Removed virtual environment at: .venv
Creating virtual environment at: .venv
Installed 12 packages in 25ms
/Users/tomoki/Dropbox/codes/contest/atcoder/ahc040/optimize.py:119: ExperimentalWarning: WilcoxonPruner is experimental (supported from v3.6.0). The interface can change in the future.
  pruner=optuna.pruners.WilcoxonPruner(),
[I 2024-12-08 00:33:19,688] A new study created in memory with name: optuna-study
[I 2024-12-08 00:39:45,803] Trial 0 finished with value: 1106381.592 and parameters: {'BEAM_WIDTH': 2, 'EVAL_MULTIPLY_SPACE': 0.5, 'QUEUE_SIZE_BASE': 'number_of_rects', 'QUEUE_MULTIPLIER': 990}. Best is trial 0 with value: 1106381.592.
[I 2024-12-08 00:46:14,873] Trial 1 finished with value: 1106247.301 and parameters: {'BEAM_WIDTH': 2, 'EVAL_MULTIPLY_SPACE': 0.6, 'QUEUE_SIZE_BASE': 'number_of_turn', 'QUEUE_MULTIPLIER': 30}. Best is trial 1 with value: 1106247.301.
^C[W 2024-12-08 00:48:26,115] Trial 2 failed with parameters: {'BEAM_WIDTH': 1, 'EVAL_MULTIPLY_SPACE': 0.9, 'QUEUE_SIZE_BASE': 'number_of_turn', 'QUEUE_MULTIPLIER': 400} because of the following error: KeyboardInterrupt().
Traceback (most recent call last):
  File "/Users/tomoki/Dropbox/codes/contest/atcoder/ahc040/.venv/lib/python3.13/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "/Users/tomoki/Dropbox/codes/contest/atcoder/ahc040/optimize.py", line 78, in __call__
    for line in process.stdout:
                ^^^^^^^^^^^^^^
KeyboardInterrupt
[W 2024-12-08 00:48:26,118] Trial 2 failed with value None.
Traceback (most recent call last):
  File "/Users/tomoki/Dropbox/codes/contest/atcoder/ahc040/optimize.py", line 123, in <module>
    run_optimization(study)
    ~~~~~~~~~~~~~~~~^^^^^^^
  File "/Users/tomoki/Dropbox/codes/contest/atcoder/ahc040/optimize.py", line 44, in run_optimization
    study.optimize(Objective(), timeout=60 * 60 * 5)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tomoki/Dropbox/codes/contest/atcoder/ahc040/.venv/lib/python3.13/site-packages/optuna/study/study.py", line 475, in optimize
    _optimize(
    ~~~~~~~~~^
        study=self,
        ^^^^^^^^^^^
    ...<7 lines>...
        show_progress_bar=show_progress_bar,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/tomoki/Dropbox/codes/contest/atcoder/ahc040/.venv/lib/python3.13/site-packages/optuna/study/_optimize.py", line 63, in _optimize
    _optimize_sequential(
    ~~~~~~~~~~~~~~~~~~~~^
        study,
        ^^^^^^
    ...<8 lines>...
        progress_bar=progress_bar,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/tomoki/Dropbox/codes/contest/atcoder/ahc040/.venv/lib/python3.13/site-packages/optuna/study/_optimize.py", line 160, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/Users/tomoki/Dropbox/codes/contest/atcoder/ahc040/.venv/lib/python3.13/site-packages/optuna/study/_optimize.py", line 248, in _run_trial
    raise func_err
  File "/Users/tomoki/Dropbox/codes/contest/atcoder/ahc040/.venv/lib/python3.13/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "/Users/tomoki/Dropbox/codes/contest/atcoder/ahc040/optimize.py", line 78, in __call__
    for line in process.stdout:
                ^^^^^^^^^^^^^^
KeyboardInterrupt
uv run optimize.py  5084.65s user 192.40s system 580% cpu 15:09.36 total
```

**Comment by mogura20** [comment]
自分のところでもSIGKILLとういうのが、このような感じで発生していました。

<img width="959" alt="スクリーンショット 2024-12-09 22 57 31" src="https://github.com/user-attachments/assets/15609e02-dbae-490f-8993-2beb24f730d6">

**Comment by tomoki** [comment]
関連？ https://github.com/terry-u16/pahcer/issues/6

**Comment by terry-u16** [comment]
こちらもご報告ありがとうございます！
やはりmac上での動作に何か問題を抱えていそうです。むむむ……。

**Comment by terry-u16** [comment]
macでメモリ不足のときにSIGKILLが送出されることがあるらしくそれを一瞬疑ったのですが、頂いたコードを見る限り幅の巨大なビームサーチをしているわけでもなさそうで、メモリが原因というわけでもなさそうですね。うーん……。

**Comment by terry-u16** [comment]
#6 と同様の手順で改善するかもしれませんので、ちょっとご確認頂ければ……！

https://github.com/terry-u16/pahcer/issues/6#issuecomment-2538764711

**Comment by tomoki** [comment]
> #6 と同様の手順で改善するかもしれませんので、ちょっとご確認頂ければ……！
> 
> [#6 (comment)](https://github.com/terry-u16/pahcer/issues/6#issuecomment-2538764711)

ありがとうございます！ https://github.com/terry-u16/pahcer/issues/6#issuecomment-2541475374 でご報告させていただいたとおり https://github.com/terry-u16/pahcer/issues/6#issuecomment-2538764711 の手順で 100 ケース x 85 回の試行でこちらの事象は再現していません 👍 

macos では cargo --run を一つのプロジェクトに対し同時に行うと何か良くないことが起こるみたいですね。。。

**Comment by terry-u16** [comment]
こちらも再現しなくなったようで良かったです。ありがとうございます！
OS別に設定ファイル変更した方が良さそうなので、どこかのタイミングで追加します……！

**Comment by terry-u16** [comment]
#12 で対応済み。
